# Generated by Django 5.0.3 on 2024-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('dish_pic', models.FileField(upload_to='')),
            ],
        ),
    ]
