# Generated by Django 5.0.3 on 2024-03-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro_app', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
    ]
